apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: hippo-snapshot-test
  namespace: postgres-operator
spec:
  volumeSnapshotClassName: gke-snapshot-class
  source:
    persistentVolumeClaimName: hippo-deltarestore
